alias gs='git status'
alias gsu='git status -uno'
alias gdi='git diff'
alias gdc='git diff --cached'
alias gdn='git diff --no-index'
alias gf='git fetch --all'
alias gitk='gitk --all &'
alias gitk2='git log --graph --abbrev-commit --pretty=oneline --decorate'
alias gp='for f in `git remote` ; do git remote prune $f ; done'
